/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidateRouteImport } from './routes/validate'
import { Route as RenderRouteImport } from './routes/render'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'

const ValidateRoute = ValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderRoute = RenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRoute
  '/render': typeof RenderRoute
  '/validate': typeof ValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRoute
  '/render': typeof RenderRoute
  '/validate': typeof ValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRoute
  '/render': typeof RenderRoute
  '/validate': typeof ValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/import' | '/locations' | '/menu' | '/render' | '/validate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/import' | '/locations' | '/menu' | '/render' | '/validate'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/locations'
    | '/menu'
    | '/render'
    | '/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  LocationsRoute: typeof LocationsRoute
  MenuRoute: typeof MenuRoute
  RenderRoute: typeof RenderRoute
  ValidateRoute: typeof ValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render': {
      id: '/render'
      path: '/render'
      fullPath: '/render'
      preLoaderRoute: typeof RenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  LocationsRoute: LocationsRoute,
  MenuRoute: MenuRoute,
  RenderRoute: RenderRoute,
  ValidateRoute: ValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
